name: Publish

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    uses: ./.github/workflows/reusable-publish.yml
    permissions:
      id-token: write
      contents: read
